### ISSUE TITLE
不在分组中

### ISSUE THREAD

**Issue by jybtx** [badidol/badidol#4]
![微信图片_20200609141245](https://user-images.githubusercontent.com/34736990/84112432-53a09480-aa5b-11ea-9764-74487a680cdd.png)

大佬，我将你的项目git下来后配置好相关的配置后，数据也迁移了，进后台管理就报这个错误，我本地的php环境是：7.2.27 ；数据库是：mariadb 10.0.38的。

SQLSTATE[42000]: Syntax error or access violation: 1055 'badidol.topics.title' isn't in GROUP BY (SQL: SELECT COUNT(id) AS aggregate FROM (select `topics`.* from `topics` group by `topics`.`id`) AS agg)

**Comment by badidol** [comment]
.env 文件发我下呢

**Comment by jybtx** [comment]
> 你好，请把.env文件发我看看呢

![微信图片_20200609185540](https://user-images.githubusercontent.com/34736990/84139649-d6891580-aa82-11ea-8d9f-b0a404a3251c.png)
这是我的 .env 文件

**Comment by badidol** [comment]
> > 你好，请把.env文件发我看看呢
> 
> ![微信图片_20200609185540](https://user-images.githubusercontent.com/34736990/84139649-d6891580-aa82-11ea-8d9f-b0a404a3251c.png)
> 这是我的 .env 文件

badidol/config/database.php 第 59 行改成 'strict' => false 试试呢

**Comment by jybtx** [comment]
> > > 你好，请把.env文件发我看看呢
> > 
> > 
> > ![微信图片_20200609185540](https://user-images.githubusercontent.com/34736990/84139649-d6891580-aa82-11ea-8d9f-b0a404a3251c.png)
> > 这是我的 .env 文件
> 
> badidol/config/database.php 第 59 行改成 'strict' => false 试试呢

好了，谢谢大佬！
